/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "DataLayout",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DataLayout__factory>;
    getContractFactory(
      name: "LibraryLock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibraryLock__factory>;
    getContractFactory(
      name: "LogicV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LogicV1__factory>;
    getContractFactory(
      name: "LogicV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LogicV2__factory>;
    getContractFactory(
      name: "Proxiable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxiable__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;

    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "DataLayout",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DataLayout>;
    getContractAt(
      name: "LibraryLock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibraryLock>;
    getContractAt(
      name: "LogicV1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LogicV1>;
    getContractAt(
      name: "LogicV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LogicV2>;
    getContractAt(
      name: "Proxiable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxiable>;
    getContractAt(
      name: "Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
